---
kind: pipeline
type: kubernetes
name: compliance

platform:
  os: linux
  arch: arm64

workspace:
  path: /drone/src

trigger:
  ref:
    - refs/tags/**
    - refs/heads/**
  event:
    exclude:
      - promote

volumes:
  - name: drone-cache-volume
    host:
      path: /var/lib/cache

image_pull_secrets:
  - dockerconfig

steps:
  - name: lint
    image: ccr.ccs.tencentyun.com/ruilisi/feishu-api-bundler
    commands:
      - make lint

---
kind: pipeline
type: kubernetes
name: sync-to-github

platform:
  os: linux
  arch: arm64

workspace:
  path: /drone/src

trigger:
  ref:
    - refs/heads/master
  event:
    exclude:
      - promote

steps:
  - name: sync commit
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: github_ssh_key
    commands:
      - mkdir -p /root/.ssh/ && echo $SSH_KEY | base64 -d > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts && chmod 600 /root/.ssh/known_hosts
      - git remote add github git@github.com:ruilisi/feishu-api.git
      - git push github ${branch:-${DRONE_BRANCH}} --force
